name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Build
        run: |
          pnpm i
          pnpm build
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

  deploy:
    needs: main
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
